### ISSUE TITLE
请问用api23的环境开发是不是不支持一些方法 还有这个项目支不支持6.0的手机使用呢？

### ISSUE THREAD

**Issue by InterestingYuTou** [mabeijianxi/small-video-record#109]

**Comment by InterestingYuTou** [comment]
Process: com.yutou, PID: 17415
                                                           java.lang.UnsatisfiedLinkError: Native method not found: com.yutou.ui.smallvideo.UtilityAdapter.FilterParserAction:(Ljava/lang/String;I)I
                                                               at com.yutou.ui.smallvideo.UtilityAdapter.FilterParserAction(Native Method)
                                                               at com.yutou.ui.smallvideo.UtilityAdapter.freeFilterParser(UtilityAdapter.java:199)
                                                               at com.yutou.ui.smallvideo.MediaRecorderActivity.onResume(MediaRecorderActivity.java:311)
它说的是这个UtilityAdapter里面的FilterParserAction这个方法找不到 而且这个适配器里面好多方法都是红色的 好像又不影响代码 不知道怎么解决

**Comment by mabeijianxi** [comment]
你先看看JNI怎么开发吧，你乱改路径肯定找不到方法的
