### ISSUE TITLE
small-video-record2 demo 运行时报错 couldn't find "libavfilter.so"

### ISSUE THREAD

**Issue by huangchenggang** [mabeijianxi/small-video-record#122]
06-23 13:53:38.838 374-374/com.mabeijianxi.smallvideo2 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.mabeijianxi.smallvideo2, PID: 374
                                                                         java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mabeijianxi.smallvideo2-1/base.apk", zip file "/data/app/com.mabeijianxi.smallvideo2-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.mabeijianxi.smallvideo2-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.mabeijianxi.smallvideo2-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.mabeijianxi.smallvideo2-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.mabeijianxi.smallvideo2-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.mabeijianxi.smallvideo2-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.mabeijianxi.smallvideo2-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.mabeijianxi.smallvideo2-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.mabeijianxi.smallvideo2-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.mabeijianxi.smallvideo2-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.mabeijianxi.smallvideo2-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.mabeijianxi.smallvideo2-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libavfilter.so"
                                                                             at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                             at java.lang.System.loadLibrary(System.java:988)
                                                                             at com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.<clinit>(FFmpegBridge.java:19)
                                                                             at com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.initJXFFmpeg(Native Method)
                                                                             at com.mabeijianxi.smallvideorecord2.JianXiCamera.initialize(JianXiCamera.java:40)
                                                                             at com.mabeijianxi.smallvideo2.MainActivity.initSmallVideo(MainActivity.java:404)
                                                                             at com.mabeijianxi.smallvideo2.MainActivity.onCreate(MainActivity.java:85)
                                                                             at android.app.Activity.performCreate(Activity.java:6117)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2594)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2710)
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:179)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                             at android.os.Looper.loop(Looper.java:194)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5803)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)

**Comment by zpliang94** [comment]
在一些机型有这样的问题，我的nexus5,红米测试时没问题，而我把SmallVideoLib作为module导入项目，红米，Nubia也有这样问题，而nexus5没有

**Comment by huangchenggang** [comment]
怎么解决啊 直接打不开 不能用了呢

**Comment by mabeijianxi** [comment]
这是很常见的问题，你用了其他型号的 SO 库，你在你用的 Module 里面添加 abiFilters "armeabi-v7a" 即可。如果你一定要用 armeabi，那直接吧 armeabi-v7a 里面的 so 拷贝到 armeabi 里面然后再添加  abiFilters "armeabi" 即可

**Comment by linqssonny** [comment]
armeabi-v7a拷到armeabi能用吗？v7向下兼容v5， 但v5不能运行v7的so文件吧？

**Comment by mabeijianxi** [comment]
可以用

**Comment by linqssonny** [comment]
目前我的项目中使用： "armeabi", "armeabi-v7a", "arm64-v8a"三个平台架构，armeabi可以拷贝过去，但arm64这个要怎么办？是不是要重新编译ffmpeg？

**Comment by mabeijianxi** [comment]
arm64 的我没试过，你可以试下，不行就改改脚本编译下就OK了。感觉没必要搞这么全，占用太大的空间了，arm 系列基本都是兼容的。

**Comment by linqssonny** [comment]
刚看了大神的博文，ndk才了解一点点，目前时间不允许，只能先兼容armeabi-v7a平台。马哥多出点博文哈，特别是ndk方面的

**Comment by zpliang94** [comment]
@linqssonny 请问你的情况是怎么解决问题的

**Comment by linqssonny** [comment]
这是很常见的问题，你用了其他型号的 SO 库，你在你用的 Module 里面添加 abiFilters "armeabi-v7a" 即可。如果你一定要用 armeabi，那直接吧 armeabi-v7a 里面的 so 拷贝到 armeabi 里面然后再添加 abiFilters "armeabi" 即可

作者说的这样

**Comment by huangchenggang** [comment]
libavfilter.so 是不是要提供64位的so库，在一些手机是会报/data/app/com.mabeijianxi.smallvideo2-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libavfilter.so"

**Comment by mabeijianxi** [comment]
@huangchenggang 你应该也是在项目中用了其他架构的so吧，然后运行demo也是没问题的？

**Comment by mabeijianxi** [comment]
我觉得这种so不全是开发者很常见的啊，你用阿里腾讯的 sdk 也没说每个平台都给啊，会变大那么多，要知道怎么处理这种情况啊。既然都这么需要全平台，正式版的时候会全部编译一份，需要什么拷什么就行了

**Comment by huangchenggang** [comment]
@mabeijianxi  项目中没有使用其他的so库，就是small-video-record2编译的apk 跑在MX5 Flyme5.1.9.0和小米Note顶配版上回出现这种错误，在华为荣耀6上是正常的

**Comment by mabeijianxi** [comment]
2.0.0 正式版刚提交完成，已编译全平台，使用方式也更加解耦，但和以前略有不同，使用前请参看使用文档！
