### ISSUE TITLE
so包报错了

### ISSUE THREAD

**Issue by 3kqing** [mabeijianxi/small-video-record#125]
java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib/libavutil.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
                                                                           at java.lang.Runtime.loadLibrary0(Runtime.java:977)
                                                                           at java.lang.System.loadLibrary(System.java:1530)
                                                                           at com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.<clinit>(FFmpegBridge.java:14)
                                                                           at com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.initJXFFmpeg(Native Method)
                                                                           at com.mabeijianxi.smallvideorecord2.JianXiCamera.initialize(JianXiCamera.java:40)

**Comment by mabeijianxi** [comment]
能详细描述下详细运行环境么，还有什么情况下报错，什么情况下不报
