### ISSUE TITLE
smallvideorecord2华为FRD-AL00启动崩溃，错误日志如下

### ISSUE THREAD

**Issue by fengfutong** [mabeijianxi/small-video-record#155]
FATAL EXCEPTION: main
                                                                             Process: com.mabeijianxi.smallvideo2, PID: 16516
                                                                             java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__powisf2" referenced by "/data/app/com.mabeijianxi.smallvideo2-1/lib/arm64/libavfilter.so"...
                                                                                 at java.lang.Runtime.loadLibrary0(Runtime.java:994)
                                                                                 at java.lang.System.loadLibrary(System.java:1533)
                                                                                 at com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.<clinit>(FFmpegBridge.java:19)
                                                                                 at com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.initJXFFmpeg(Native Method)
                                                                                 at com.mabeijianxi.smallvideorecord2.JianXiCamera.initialize(JianXiCamera.java:40)
                                                                                 at com.mabeijianxi.smallvideo2.MainActivity.initSmallVideo(MainActivity.java:434)
                                                                                 at com.mabeijianxi.smallvideo2.MainActivity.onCreate(MainActivity.java:88)
                                                                                 at android.app.Activity.performCreate(Activity.java:6910)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                 at android.os.Looper.loop(Looper.java:156)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6531)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by mabeijianxi** [comment]
今天的最新代码吗？

**Comment by mabeijianxi** [comment]
我记得我已经去掉了这个 so 的加载了，看看直接扫描二维码的 sample 会不会有问题

**Comment by fengfutong** [comment]
我昨天晚上clone的最新master代码，二维码的apk可以用，但是选择视频并压缩，并没有任何反应

**Comment by fengfutong** [comment]
原来你在sample中的mainactivity中弹出的toast没有调用show()。我说这既然拿不到uri，怎么连toast也弹不出来了^ - ^

**Comment by mabeijianxi** [comment]
额。。哈哈哈哈我靠。。。
