### ISSUE TITLE
PortUnreachableException和com.huawei.lcagent.client.LogCollectManager.getUserType() NullPointerException

### ISSUE THREAD

**Issue by xiaobaicaiya** [mabeijianxi/small-video-record#160]
@mabeijianxi 不管是在此之前的lib2.0版本还是最新的，在vivo Xplay5 android5.1.1上初始化报错，
07-06 10:05:52.755 21567-18931/com.forms.phonehelper:remote W/System.err: java.net.PortUnreachableException: 
07-06 10:05:52.755 21567-18931/com.forms.phonehelper:remote W/System.err:     at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:595)
07-06 10:05:52.756 21567-18931/com.forms.phonehelper:remote W/System.err:     at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
07-06 10:05:52.757 21567-18931/com.forms.phonehelper:remote W/System.err:     at java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:177)
07-06 10:05:52.758 21567-18931/com.forms.phonehelper:remote W/System.err:     at java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:185)
07-06 10:05:52.758 21567-18931/com.forms.phonehelper:remote W/System.err:     at java.net.DatagramSocket.receive(DatagramSocket.java:250)
07-06 10:05:52.759 21567-18931/com.forms.phonehelper:remote W/System.err:     at org.ddpush.im.v1.client.appuser.UDPClientBase.receiveData(UDPClientBase.java:212)
07-06 10:05:52.759 21567-18931/com.forms.phonehelper:remote W/System.err:     at org.ddpush.im.v1.client.appuser.UDPClientBase.run(UDPClientBase.java:171)
07-06 10:05:52.760 21567-18931/com.forms.phonehelper:remote W/System.err:     at java.lang.Thread.run(Thread.java:841)
07-06 10:05:52.760 21567-18931/com.forms.phonehelper:remote W/System.err: Caused by: libcore.io.ErrnoException: recvfrom failed: ECONNREFUSED (Connection refused)
07-06 10:05:52.761 21567-18931/com.forms.phonehelper:remote W/System.err:     at libcore.io.Posix.recvfromBytes(Native Method)
07-06 10:05:52.761 21567-18931/com.forms.phonehelper:remote W/System.err:     at libcore.io.Posix.recvfrom(Posix.java:141)
07-06 10:05:52.762 21567-18931/com.forms.phonehelper:remote W/System.err:     at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
07-06 10:05:52.762 21567-18931/com.forms.phonehelper:remote W/System.err:     at libcore.io.IoBridge.recvfrom(IoBridge.java:550)
07-06 10:05:52.763 21567-18931/com.forms.phonehelper:remote W/System.err: 	... 6 more
07-06 10:05:56.344 760-1208/? W/Parcel: Attempt to read object from Parcel 0x7b98c61c at offset 68 that is not in the object list
另外在华为上面也报错：
com.huawei.lcagent.client.LogCollectManager.getUserType() NullPointerException
没有具体的错误日志，就这么一句，懵逼

**Comment by mabeijianxi** [comment]
这包名看着不是我项目的，你是扫码下载的 apk 么？

**Comment by xiaobaicaiya** [comment]
@mabeijianxi 不是，直接compile 'com.mabeijianxi:small-video-record2:2.0.0@aar'然后调方法压缩视频

**Comment by xiaobaicaiya** [comment]
但是在初始化华为上初始化就崩溃了，xplay5上解压时候刚刚试了下新的库，初始化也报错：
07-06 10:53:04.882 7950-7950/com.example.formssi.firsttest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.example.formssi.firsttest, PID: 7950
                                                                             java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.formssi.firsttest-2/base.apk", zip file "/data/app/com.example.formssi.firsttest-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.formssi.firsttest-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.formssi.firsttest-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.formssi.firsttest-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.formssi.firsttest-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.formssi.firsttest-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.formssi.firsttest-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.formssi.firsttest-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.formssi.firsttest-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.formssi.firsttest-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.formssi.firsttest-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.formssi.firsttest-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libavutil.so"
                                                                                 at java.lang.Runtime.loadLibrary(Runtime.java:370)
                                                                                 at java.lang.System.loadLibrary(System.java:988)
                                                                                 at com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.<clinit>(FFmpegBridge.java:14)
                                                                                 at com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.initJXFFmpeg(Native Method)
                                                                                 at com.mabeijianxi.smallvideorecord2.JianXiCamera.initialize(JianXiCamera.java:40)
                                                                                 at com.example.formssi.firsttest.APP.initSmallVideo(APP.java:41)
                                                                                 at com.example.formssi.firsttest.APP.onCreate(APP.java:22)
                                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1021)
                                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4681)
                                                                                 at android.app.ActivityThread.access$1600(ActivityThread.java:175)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5413)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:927)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:722)

**Comment by mabeijianxi** [comment]
你是不是没按照最新文档操作，是不是没复制最新的 so 文件到主项目

**Comment by xiaobaicaiya** [comment]
谢谢，我刚去看了，2.0还要手动导入so  0.0，thank you,赶紧试试
