### ISSUE TITLE
vivo Xplay 5上安装small-video-record2  apk依然报错

### ISSUE THREAD

**Issue by xiaobaicaiya** [mabeijianxi/small-video-record#161]
@mabeijianxi 大神：
在vivo Xplay 5 android 5.1.1 依然报错，你的small-video-record2  apk那个我下下来在上面运行也报错，到是在lenovo和酷派的手机上面运行完好，包括自己工程引入small-video-record2库：
07-06 13:36:40.062 18609-18609/com.spreadit.spreaditapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.spreadit.spreaditapp, PID: 18609
                                                                          java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__powidf2" referenced by "libswresample.so"...
                                                                              at java.lang.Runtime.loadLibrary(Runtime.java:375)
                                                                              at java.lang.System.loadLibrary(System.java:988)
                                                                              at com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.<clinit>(FFmpegBridge.java:19)
                                                                              at com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.initJXFFmpeg(Native Method)
                                                                              at com.mabeijianxi.smallvideorecord2.JianXiCamera.initialize(JianXiCamera.java:40)
                                                                              at com.spreadit.spreaditapp.activity.task.PostPreviewActivity.initSmall_Video_Record(PostPreviewActivity.java:864)
                                                                              at com.spreadit.spreaditapp.activity.task.PostPreviewActivity.onCreate(PostPreviewActivity.java:86)
                                                                              at android.app.Activity.performCreate(Activity.java:6089)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:175)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5413)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:927)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:722)

**Comment by xiaobaicaiya** [comment]
另外，昨天更新small-video-record2库之前vivo xplay5是可以的，就是华为的NXT -AL10不行，今天就反过来了，华为的没有问题了

**Comment by mabeijianxi** [comment]
libswresample.so 这个so 在最新代码中 Java 层我已经除掉了啊，怎么还去链接，确定没装错吧

**Comment by xiaobaicaiya** [comment]
@mabeijianxi 
没有，我直接在这里扫码安装的那个demo2，而且只在我的xplay5上面报错，其他机型正常运行，刚刚我再下载一次demo试了一下，还是这样的.另外 错误指向FFmpegBridge 中的System.loadLibrary("jx_ffmpeg_jni");

**Comment by mabeijianxi** [comment]
好吧我查下吧

**Comment by mabeijianxi** [comment]
问题已经修复，是我编译的是否加入了个 m 的数学函数库，结果有的手机不支持。。。，2.0.1 已经修复，你们再试试，没问题就关了

**Comment by xiaobaicaiya** [comment]
可以了，完美
