### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__powisf2"

### ISSUE THREAD

**Issue by epolar** [mabeijianxi/small-video-record#169]
求问，报的这个错：
```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__powisf2" referenced by "/data/app/xyz.eraise.camerarecord-1/lib/arm64/libavfilter.so"...
at java.lang.Runtime.loadLibrary(Runtime.java:372)
at java.lang.System.loadLibrary(System.java:1076)
at com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.<clinit>(FFmpegBridge.java:18)
at com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.initJXFFmpeg(Native Method)
at com.mabeijianxi.smallvideorecord2.JianXiCamera.initialize(JianXiCamera.java:40)
at xyz.eraise.camerarecord.MyApplication.onCreate(MyApplication.java:35)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1026)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5000)
at android.app.ActivityThread.access$1600(ActivityThread.java:150)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1455)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:168)
at android.app.ActivityThread.main(ActivityThread.java:5781)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
```

我是通过远程包导入的方式做的，已经把all_lib复制到 main/jniLibs 下了

**Comment by mabeijianxi** [comment]
这个问题我已经在2.0.1上修复了，更新下so 与代码

**Comment by epolar** [comment]
感谢，问题的确解决了。
