### ISSUE TITLE
华为荣耀系列闪退

### ISSUE THREAD

**Issue by Lupwsky** [mabeijianxi/small-video-record#200]
两台华为荣耀的手机，一台是4.2.2的系统，一台是6.0的系统都闪退了

**Comment by Lupwsky** [comment]
华为荣耀3C上报的错误：
java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1654): could not load library "libswscale.so" needed by "libavfilter.so"; caused by load_library(linker.cpp:761): library "libswscale.so" not found
                                                                                 at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                                 at java.lang.System.loadLibrary(System.java:514)
                                                                                 at com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.<clinit>(FFmpegBridge.java:18)
                                                                                 at com.mabeijianxi.smallvideorecord2.JianXiCamera.initialize(JianXiCamera.java:40)
                                                                                 at com.mabeijianxi.smallvideo2.MainActivity.initSmallVideo(MainActivity.java:434)
                                                                                 at com.mabeijianxi.smallvideo2.MainActivity.onCreate(MainActivity.java:88)
                                                                                 at android.app.Activity.performCreate(Activity.java:5211)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1146)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2336)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2424)
                                                                                 at android.app.ActivityThread.access$600(ActivityThread.java:169)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                 at android.os.Looper.loop(Looper.java:194)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5433)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
                                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by mabeijianxi** [comment]
用 dev 分支试试，修复了，还没合并到主分支

**Comment by mabeijianxi** [comment]
2.0.3已修复，请确认

**Comment by Lupwsky** [comment]
@mabeijianxi 谢谢大神~~~
