### ISSUE TITLE
魅族4.4.4加载so库的时候闪退了

### ISSUE THREAD

**Issue by Lupwsky** [mabeijianxi/small-video-record#214]
Process: com.mabeijianxi.smallvideo2, PID: 8865
                                                 java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_audio_fifo_peek" referenced by "libavfilter.so"...
                                                     at java.lang.Runtime.loadLibrary(Runtime.java:364)
                                                     at java.lang.System.loadLibrary(System.java:538)
                                                     at com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.<clinit>(FFmpegBridge.java:20)
                                                     at com.mabeijianxi.smallvideorecord2.JianXiCamera.initialize(JianXiCamera.java:40)
                                                     at com.mabeijianxi.smallvideo2.MainActivity.initSmallVideo(MainActivity.java:433)
                                                     at com.mabeijianxi.smallvideo2.MainActivity.onCreate(MainActivity.java:88)
                                                     at android.app.Activity.performCreate(Activity.java:5340)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1099)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2235)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2320)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:138)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5117)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by Lupwsky** [comment]
跑的是项目里面的例子

**Comment by mabeijianxi** [comment]
额。。。好吧，我看能找个mx3手机不。。。我这一堆魅族，mx6pro,mx4,mx4pro...

**Comment by altair441n** [comment]
@mabeijianxi 你好，我使用乐事letv x500也报了同样的错误，android5.0.2，请问有什么解决办法。

**Comment by zhangh01** [comment]
也是一样魅族手机会碰到这个问题。Demo 和自己的项目都会崩溃
魅族 android 4.4.4  型号 m1 Flyme 
 java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_audio_fifo_peek" referenced by "libavfilter.so"...
                                                                                 at java.lang.Runtime.loadLibrary(Runtime.java:378)
                                                                                 at java.lang.System.loadLibrary(System.java:540)
                                                                                 at com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.<clinit>(FFmpegBridge.java:20)
                                                                                 at com.mabeijianxi.smallvideorecord2.JianXiCamera.initialize(JianXiCamera.java:40)
                                                                                 at com.mabeijianxi.smallvideo2.MainActivity.initSmallVideo(MainActivity.java:433)
                                                                                 at com.mabeijianxi.smallvideo2.MainActivity.onCreate(MainActivity.java:88)
                                                                                 at android.app.Activity.performCreate(Activity.java:5451)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2346)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2443)
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:157)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                 at android.os.Looper.loop(Looper.java:193)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5348)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
