### ISSUE TITLE
魅族mx4 三星手机录制视频时返回,程序崩溃

### ISSUE THREAD

**Issue by smallheart** [mabeijianxi/small-video-record#222]
Exception dealing with report
android.system.ErrnoException: read failed: EAGAIN (Try again)

**Comment by mabeijianxi** [comment]
其他手机都可以，魅族mx4不太能啊啊啊，我就用它开发的调试了无数次，有稍微全点信息么

**Comment by smallheart** [comment]
NativeCrashListener: Exception dealing with report
                                                                   android.system.ErrnoException: read failed: EAGAIN (Try again)
                                                                       at libcore.io.Posix.readBytes(Native Method)
                                                                       at libcore.io.Posix.read(Posix.java:165)
                                                                       at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
                                                                       at android.system.Os.read(Os.java:350)
                                                                       at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
                                                                       at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)
