### ISSUE TITLE
加载so库失败

### ISSUE THREAD

**Issue by T-BayMax** [mabeijianxi/small-video-record#230]
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.ike.communityalliance/app_p_n/419924309/libutility.so" has unexpected e_machine: 40
                                                                        at java.lang.Runtime.loadLibrary0(Runtime.java:977)
                                                                        at java.lang.System.loadLibrary(System.java:1530)
                                                                        at com.yixia.videoeditor.adapter.UtilityAdapter.<clinit>(UtilityAdapter.java:10)
                                                                        at mabeijianxi.camera.i.a(VCamera.java:48)

**Comment by MakeCodeFly** [comment]
同问

**Comment by amelons** [comment]
同问
