### ISSUE TITLE
compileSdkVersion使用23编译,发现崩溃

### ISSUE THREAD

**Issue by SmithLiang** [mabeijianxi/small-video-record#24]
1-24 16:19:08.343 4358-4358/com.mabeijianxi.smallvideo W/System.err: java.io.IOException: open failed: ENOENT (No such file or directory)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at java.io.File.createNewFile(File.java:939)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at mabeijianxi.camera.VCamera.setVideoCachePath(VCamera.java:111)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at com.mabeijianxi.smallvideo.MainActivity.initSmallVideo(MainActivity.java:52)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at com.mabeijianxi.smallvideo.MainActivity.onCreate(MainActivity.java:22)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at android.app.Activity.performCreate(Activity.java:6298)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1576)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:111)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at android.os.Looper.loop(Looper.java:207)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5905)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at libcore.io.Posix.open(Native Method)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
11-24 16:19:08.347 4358-4358/com.mabeijianxi.smallvideo W/System.err:     at java.io.File.createNewFile(File.java:932)
11-24 16:19:08.348 4358-4358/com.mabeijianxi.smallvideo W/System.err: 	... 15 more
11-24 16:19:08.355 4358-4358/com.mabeijianxi.smallvideo D/AndroidRuntime: Shutting down VM
11-24 16:19:08.355 4358-4358/com.mabeijianxi.smallvideo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.mabeijianxi.smallvideo, PID: 4358
                                                                          java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.mabeijianxi.smallvideo-1/lib/arm/libutility.so: has text relocations
                                                                              at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                              at java.lang.System.loadLibrary(System.java:1076)
                                                                              at com.yixia.videoeditor.adapter.UtilityAdapter.<clinit>(UtilityAdapter.java:10)
                                                                              at mabeijianxi.camera.VCamera.initialize(VCamera.java:48)
                                                                              at com.mabeijianxi.smallvideo.MainActivity.initSmallVideo(MainActivity.java:57)
                                                                              at com.mabeijianxi.smallvideo.MainActivity.onCreate(MainActivity.java:22)
                                                                              at android.app.Activity.performCreate(Activity.java:6298)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
                                                                              at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1576)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                              at android.os.Looper.loop(Looper.java:207)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5905)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)

**Comment by mabeijianxi** [comment]
这是个已知问题，暂时只适用于targetSdkVersion23以下开发
