### ISSUE TITLE
Meizu M1 android4.4.4 so文件错误

### ISSUE THREAD

**Issue by HolickABC** [mabeijianxi/small-video-record#256]
我这边已经使用了全部架构，版本是2.0.3，截图传失败了，我就直接粘贴了哈

FATAL EXCEPTION: main
                                                             Process: com.bbetter, PID: 24360
                                                             java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_audio_fifo_peek" referenced by "libavfilter.so"...
                                                                 at java.lang.Runtime.loadLibrary(Runtime.java:378)
                                                                 at java.lang.System.loadLibrary(System.java:540)
                                                                 at com.mabeijianxi.smallvideorecord2.jniinterface.FFmpegBridge.<clinit>(FFmpegBridge.java:20)
                                                                 at com.mabeijianxi.smallvideorecord2.JianXiCamera.initialize(JianXiCamera.java:40)
                                                                 at com.bbetter.application.MyApplication.initRecordSDK(MyApplication.java:97)
                                                                 at com.bbetter.application.MyApplication.onCreate(MyApplication.java:33)
                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016)
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4590)
                                                                 at android.app.ActivityThread.access$1500(ActivityThread.java:157)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                 at android.os.Looper.loop(Looper.java:193)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5348)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by MakeCodeFly** [comment]
我也遇到这个问题了
