### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.hcf.client-1/lib/arm/libutility.so: has text relocations

### ISSUE THREAD

**Issue by vanszhen** [mabeijianxi/small-video-record#315]
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.hcf.client-1/lib/arm/libutility.so: has text relocations
                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                  at java.lang.System.loadLibrary(System.java:1076)
                                                                  at com.yixia.videoeditor.adapter.UtilityAdapter.<clinit>(UtilityAdapter.java:10)
                                                                  at com.yixia.videoeditor.adapter.UtilityAdapter.FFmpegInit(Native Method)
                                                                  at mabeijianxi.camera.VCamera.initialize(VCamera.java:48)
                                                                  at 
大神，用SmallVideoRecord1 .so  在小米手机报错，华为也出现  ，请问下如何解决

**Comment by patience2013** [comment]
老哥解决没有？

**Comment by Zander2014** [comment]
@vanszhen 这个问题是android 6.0以后，对so动态库添加的限制，不能有text relocations，网上也有解决方法，一种是，重新编译so，但是这里是不行了，因为没有源码。另一种就是把buildToolsVersion降到23以下，这样不会报错，但是有的手机启动后，会弹出一个警告Dialog，体验不是很好，但是能用。最好的解决办法，还是仔细研究SmallVideoRecord2（有源码），然后自己去定制化和完善。
参考这个链接：http://blog.csdn.net/ahence/article/details/68953878
