### ISSUE TITLE
small-video-r2cord2录视频时多次点击录制按钮，录制结束出现奔溃bug

### ISSUE THREAD

**Issue by yaoxin2017** [mabeijianxi/small-video-record#368]
java.lang.RuntimeException: Unable to destroy activity {com.feidi.didaplatform/com.mabeijianxi.smallvideorecord2.MediaRecorderActivity}: java.util.ConcurrentModificationException
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4505)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4523)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:176)
        at com.feidi.dida.execption.CrashHandler$1.run(CrashHandler.java:53)
        at android.os.Handler.handleCallback(Handler.java:792)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.util.ConcurrentModificationException
        at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
        at java.util.LinkedList$ListItr.next(LinkedList.java:888)
        at com.mabeijianxi.smallvideorecord2.MediaRecorderBase.stopAllRecord(MediaRecorderBase.java:486)
        at com.mabeijianxi.smallvideorecord2.MediaRecorderBase.release(MediaRecorderBase.java:695)
        at com.mabeijianxi.smallvideorecord2.MediaRecorderActivity.onDestroy(MediaRecorderActivity.java:690)
        at android.app.Activity.performDestroy(Activity.java:7252)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)

**Comment by HoseaDev** [comment]
MediaRecorderActivity
的mOnVideoControllerTouchListener这个监听里面
     case MotionEvent.ACTION_UP:
下面再加下取消
                case MotionEvent.ACTION_CANCEL:
就可以了
