### ISSUE TITLE
这个如果targetSdkVersion 大于22的怎么弄弄呀?

### ISSUE THREAD

**Issue by kris-liutao** [mabeijianxi/small-video-record#72]

**Comment by kris-liutao** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.zontonec.ztkid, PID: 1313
                  java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.zontonec.ztkid-2/lib/arm/libutility.so: has text relocations
                      at java.lang.Runtime.loadLibrary(Runtime.java:372)
                      at java.lang.System.loadLibrary(System.java:1076)
                      at com.yixia.videoeditor.adapter.UtilityAdapter.<clinit>(UtilityAdapter.java:10)
                      at mabeijianxi.camera.VCamera.initialize(VCamera.java:48)
                      at com.zontonec.ztkid.App.initSmallVideo(App.java:79)
                      at com.zontonec.ztkid.App.onCreate(App.java:39)
                      at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4726)
                      at android.app.ActivityThread.access$1600(ActivityThread.java:153)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5438)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
报了个这错误怎么解决呀！

**Comment by IdioticMadman** [comment]
出现 java.lang.UnsatisfiedLinkError错误可以尝试在gradle.properties中添加：android.useDeprecatedNdk=true，然后在主module的build.gradle中配置ndk {abiFilters "armeabi", "armeabi-v7a"}

**Comment by mankind-evolve** [comment]
crash:java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.lazy.android-1/lib/arm/libutility.so: has text relocations

我的也是这样，   

在gradle.properties中添加：android.useDeprecatedNdk=true，然后在主module的build.gradle中配置ndk {abiFilters "armeabi", "armeabi-v7a"}

这个也加过了   好像是so的路径不对

**Comment by kris-liutao** [comment]
@mankind-evolve @IdioticMadman 恩恩 这种我也试过了   最后在主模块的build.gradle中添加 
sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
}
这个解决的，我在三星手机上不会出问题，小米上就出现这个问题

**Comment by kris-liutao** [comment]
@IdioticMadman @mankind-evolve @mabeijianxi 
MediaRecorderActivity这个类下箭头指的这个地方需要传参数给    SendSmallVideoActivity
 **module = intent.getStringExtra("module");**这个地方    为什么传过去的是空啊？还需要其他地方配置吗？
MediaRecorderActivity
/**
     * @param context
     * @param overGOActivityName 录制结束后需要跳转的Activity全类名
     */
    public static void goSmallVideoRecorder(Activity context, String overGOActivityName, -----》String module, 《-------MediaRecorderConfig mediaRecorderConfig) {
        MODULE = module;
        context.startActivity(new Intent(context, MediaRecorderActivity.class).putExtra(OVER_ACTIVITY_NAME, overGOActivityName)

-------》.putExtra(MODEL, model)《---------.

putExtra(MEDIA_RECORDER_CONFIG_KEY, mediaRecorderConfig));
    } 


SendSmallVideoActivity

Intent intent = getIntent();
        //获取录制视频的地址
        videoUri = intent.getStringExtra(MediaRecorderActivity.VIDEO_URI);
        videoScreenshot = intent.getStringExtra(MediaRecorderActivity.VIDEO_SCREENSHOT);
       

        **module = intent.getStringExtra("module");**


        Bitmap bitmap = BitmapFactory.decodeFile( videoScreenshot);
        iv_video_screenshot.setImageBitmap(bitmap);
        et_send_content.setHint("记录孩子的每个成长瞬间...");
        drr.clear();
        drr.add(videoUri);

**Comment by mabeijianxi** [comment]
已提交small-video-record2欢迎尝试
