### ISSUE TITLE
Didn't find class "mabeijianxi.camera.R$id" on path: DexPathList[[zip file "/data/app/com.mr.av-2/base.apk"],nativeLibraryDirectories=[/data/app/com.mr.av-2/lib/arm, /vendor/lib, /system/lib]]

### ISSUE THREAD

**Issue by fpl1104** [mabeijianxi/small-video-record#79]
大神,我仔细检查过来,manifest文件中注册过了mabeijianxi.camera.MediaRecorderActivity,集成方式是gradle集成的,这是为什么呢?

**Comment by fpl1104** [comment]
我.so文件放在app下可是这个错

**Comment by fpl1104** [comment]
: In thread: Thread[main,5,main]
                                                       UncaughtException detected: java.lang.NoClassDefFoundError: Failed resolution of: Lmabeijianxi/camera/R$id;
                                                           at mabeijianxi.camera.MediaRecorderActivity.loadViews(MediaRecorderActivity.java:186)
                                                           at mabeijianxi.camera.MediaRecorderActivity.onCreate(MediaRecorderActivity.java:157)
                                                           at android.app.Activity.performCreate(Activity.java:6078)
                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2381)
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                           at android.app.ActivityThread.access$1200(ActivityThread.java:159)
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                           at android.os.Looper.loop(Looper.java:135)
                                                           at android.app.ActivityThread.main(ActivityThread.java:5569)
                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "mabeijianxi.camera.R$id" on path: DexPathList[[zip file "/data/app/com.mr.av-2/base.apk"],nativeLibraryDirectories=[/data/app/com.mr.av-2/lib/arm, /vendor/lib, /system/lib]]
                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                           at mabeijianxi.camera.MediaRecorderActivity.loadViews(MediaRecorderActivity.java:186) 
                                                           at mabeijianxi.camera.MediaRecorderActivity.onCreate(MediaRecorderActivity.java:157) 
                                                           at android.app.Activity.performCreate(Activity.java:6078) 
                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109) 
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2381) 
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                           at android.app.ActivityThread.access$1200(ActivityThread.java:159) 
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                           at android.os.Looper.loop(Looper.java:135) 
                                                           at android.app.ActivityThread.main(ActivityThread.java:5569) 
                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931) 
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726) 
                                                       	Suppressed: java.lang.ClassNotFoundException: mabeijianxi.camera.R$id
                                                           at java.lang.Class.classForName(Native Method)
                                                           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                           		... 16 more
                                                        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by fpl1104** [comment]
大神,这是全部的错误信息,哪里错了呢?

**Comment by zpliang94** [comment]
@fpl1104 问题可以了吗

**Comment by mabeijianxi** [comment]
2.0.0 正式版刚提交完成，已编译全平台，使用方式也更加解耦，但和以前略有不同，使用前请参看使用文档！
